name: "CI"

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      # Use "false" means a single failed build won't terminate other combinations
      # in the matrix. This wastes CPU time, but is an important debugging tool to
      # prevent a single broken platform from stopping the whole matrix.
      fail-fast: false

      matrix:
        os:
          # name: OS name (only a name for humans to read).
          # libc: userland libc, "GNU" or "musl"
          #       (only a name for humans to read)
          # ancient: true or false.
          #          true: incompatible with GitHub's actions/checkout due to
          #                node.js compatibility problem. Manual git checkout
          #                required.
          #          false: use standard GitHub's actions/checkout.
          # docker-image: string, image on DockerHub to use
          - name: "CentOS 7"
            libc: "GNU"
            ancient: true
            docker-image: "centos:7"

          - name: "Ubuntu 14.04"
            libc: "GNU"
            ancient: true
            docker-image: "ubuntu:14.04"

          - name: "Debian oldoldstable"
            libc: "GNU"
            ancient: false
            docker-image: "debian:oldoldstable"

          - name: "Debian oldstable"
            libc: "GNU"
            ancient: false
            docker-image: "debian:oldstable"

          - name: "Debian"
            libc: "GNU"
            ancient: false
            docker-image: "debian:latest"

          - name: "Ubuntu"
            libc: "GNU"
            ancient: false
            docker-image: "ubuntu:latest"

          - name: "Fedora"
            libc: "GNU"
            ancient: false
            docker-image: "fedora:latest"

          - name: "AlmaLinux 8"
            libc: "GNU"
            ancient: false
            docker-image: "almalinux:8"

          - name: "AlmaLinux Latest"
            libc: "GNU"
            ancient: false
            docker-image: "almalinux:latest"

          - name: "Alpine"
            libc: "musl"
            ancient: false
            docker-image: "alpine:latest"

    container:
      image: ${{ matrix.os.docker-image }}

    name: "${{ matrix.os.libc }}/Linux (${{ matrix.os.name }})"

    steps:
      - name: Check for dockerenv file
        # bash is not installed on Alpine at this point
        shell: sh
        run: (ls /.dockerenv && echo Found dockerenv) || exit 1

      - name: Install dependencies
        shell: sh
        run: |
          touch ~/.bash_profile  # set environmental variables here
          echo 'export CXXFLAGS="-Wall -Wextra -Wno-error"' >> ~/.bash_profile

          if grep -q "ID=fedora" /etc/os-release; then
            dnf install -y gcc gcc-c++ cmake
          elif grep -q 'ID="almalinux"' /etc/os-release; then
            dnf install -y epel-release
            dnf config-manager --set-enabled powertools || dnf config-manager --set-enabled crb

            dnf install -y gcc gcc-c++ cmake
          elif grep -q "ID=debian" /etc/os-release || grep -q "ID=ubuntu" /etc/os-release; then
            # retry failed downloads 3 times
            echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries
            apt-get update
            apt-get install -y build-essential

            if grep -q 'VERSION_ID="14.04"' /etc/os-release; then
              # Ubuntu 14.04 is incompatible with actions/checkout@v4
              apt-get install -y git

              # Ubuntu 14.04 has CMake 2 by default, but we require CMake 3
              apt-get install -y cmake3
            else
              apt-get install -y cmake
            fi
          elif grep -q "ID=alpine" /etc/os-release; then
            apk add bash build-base cmake
          elif [ -f /etc/centos-release ]; then
            # IPv6 on GitHub Actions is broken, causing random network failures
            # if a CDN rosolves to IPv6.
            echo "ip_resolve=4" >> /etc/yum.conf

            # CentOS repos are EOL and desupported
            sed -i 's|^mirrorlist|#mirrorlist|g; s|^#baseurl|baseurl|g; s|mirror.centos.org|vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-Base.repo

            yum install -y centos-release-scl || true
            sed -i 's|^mirrorlist|#mirrorlist|g; s|^#baseurl|baseurl|g;
                    s|^# baseurl|baseurl|g; s|mirror.centos.org|vault.centos.org|g' \
                /etc/yum.repos.d/CentOS-SCLo-scl.repo \
                /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
            cat /etc/yum.repos.d/CentOS-SCLo-scl.repo
            cat /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

            yum install -y epel-release
            yum install -y git
            yum install -y gcc gcc-c++ \
                           make cmake3

            # use cmake3 instead of default cmake2
            alternatives --install /usr/local/bin/cmake cmake /usr/bin/cmake3 99
          else
            echo "Unknown system!"
            exit 1
          fi

      - if: ${{ ! matrix.os.ancient }}
        name: Checkout fparser.git
        uses: actions/checkout@v4
        with:
          path: fparser

      - if: ${{ matrix.os.ancient }}
        name: Checkout fparser.git (legacy system only)
        run: |
          echo "Clone $GITHUB_SHA from $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git fparser
          cd $GITHUB_WORKSPACE/fparser

          git fetch --force $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git "+refs/heads/*:refs/remotes/origin/*"
          git fetch --force $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git "+refs/pull/*/merge:refs/remotes/origin/pr/*"
          git checkout $GITHUB_SHA

      - name: Build and install fparser
        run: |
          source ~/.bash_profile
          cd $GITHUB_WORKSPACE/fparser
          mkdir build && cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/opt
          make -j`nproc` && make install

  macOS:
    name: "macOS (ARM, latest)"

    runs-on: macos-latest
    steps:
      - name: Install dependencies
        shell: sh
        run: |
          echo "export NCPUS=$(sysctl -n hw.ncpu)" >> ~/.zprofile
          echo 'export CXXFLAGS="-Wall -Wextra -Wno-error"' >> ~/.zprofile
          brew install cmake

      - name: Checkout fparser.git
        uses: actions/checkout@v4

      - name: Build and install fparser
        run: |
          source ~/.zprofile
          mkdir build && cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/opt
          make -j$NCPUS && make install

  FreeBSD:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        machine:
          - name: "FreeBSD 14.2"
            os: freebsd
            arch: x86-64
            version: '14.2'

          # macOS already tests ARM for us, so disable the slow ARM emulator
          # for now
          #- name: "FreeBSD 14.2 (ARM emulator)"
          #  os: freebsd
          #  arch: arm64
          #  version: '14.2'

    name: "${{ matrix.machine.name }}"

    steps:
      - name: Checkout fparser.git
        uses: actions/checkout@v4

      - name: Test in FreeBSD ${{ matrix.machine.version }} ${{ matrix.machine.arch }}
        uses: cross-platform-actions/action@v0.26.0
        with:
          cpu_count: 4
          architecture: ${{ matrix.machine.arch }}
          operating_system: ${{ matrix.machine.os }}
          version: ${{ matrix.machine.version }}
          sync_files: runner-to-vm
          run: |
            echo "Install dependencies..."
            sudo pkg install -y cmake

            export NCPUS=$(sysctl -n hw.ncpu)
            export CXXFLAGS="-Wall -Wextra -Wno-error"

            echo "Build and install fparser..."
            mkdir build && cd build
            cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/opt
            make -j$NCPUS && make install
